### ISSUE TITLE
제목 : 이미지 탭의 행 클릭 시 Error 발생

### ISSUE THREAD

**Issue by kwj00310** [WoongJiKang/PyKakao#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\woong\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\woong\Documents\GitHub\PyKakao\run.py", line 154, in open_url_in_browser
    url_index = tree['columns'].index('url')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: tuple.index(x): x not in tuple

TTk모듈의 Treeview에서 url만 수집하다보니 이미지 탭에선 doc_url을 불러와야 하는데 url이 없다고 오류가 발생함

**Comment by woong020477** [comment]
기존코드
# URL 열의 인덱스 확인
            url_index = tree['columns'].index('url')

            # 선택된 아이템의 URL 가져오기
            url = item_values[url_index]

수정된 코드
# URL 열의 인덱스 확인 후 URL 가져오기
            url_columns = ['url', 'doc_url']
            url = None
            for col in url_columns:
                if col in tree['columns']:
                    url_index = tree['columns'].index(col)
                    url = item_values[url_index]
                    break
url 문자열로 구성된 열의 index만 가져오던 것을 url과 doc_url 두 개 모두 가져올 수 있도록 수정했음

**Comment by woong020477** [comment]
해결 완료 [커밋 결과](https://github.com/WoongJiKang/PyKakao/commit/85e8bffa16d1c89b250d7457d709ede6c9771cd2)
