### ISSUE TITLE
send_message.py 예제 관련 의문사항

### ISSUE THREAD

**Issue by woong020477** [WoongJiKang/PyKakao#3]
문제 코드
-------------
	from PyKakao import Message
	API = Message(service_key = "api키")

	auth_url = API.get_url_for_generating_code()
	print(auth_url)

예제에 필수적인 값을 모두 기입 후 실행 시 예제가 정상 작동하긴 하나,
이후 추가 실행 시 Redirect URI 관련 오류가 발생함

**Comment by kwj00310** [comment]
![답변](https://github.com/WoongJiKang/PyKakao/assets/76575480/a84f14d6-943d-46c4-aa2e-af9e4227bac7)
일회성 토큰이기에 지속사용이 불가함. 카카오 develop에 질문을 남겨서 온 답 첨부
